#!/usr/bin/env bash
set -euo pipefail

if [[ "${EUID}" -ne 0 ]]; then
  exec sudo -- "$0" "$@"
fi

APP_USER="${SUDO_USER:-stefano}"
APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${APP_DIR}/.env.alerts"
PJSIP_MAIN="/etc/asterisk/pjsip.conf"
PJSIP_HOMEPI="/etc/asterisk/pjsip_homepi.conf"
INCLUDE_LINE="#include pjsip_homepi.conf"
TRUNK_NAME="homepi-provider"

die() {
  echo "ERROR: $*" >&2
  exit 1
}

require_scalar() {
  local label="$1"
  local value="$2"
  [[ -n "${value}" ]] || die "${label} darf nicht leer sein."
  [[ "${value}" != *$'\n'* && "${value}" != *$'\r'* ]] || die "${label} enthält einen Zeilenumbruch."
}

require_token() {
  local label="$1"
  local value="$2"
  require_scalar "${label}" "${value}"
  [[ "${value}" =~ ^[A-Za-z0-9_.:@+-]+$ ]] || die "${label} enthält Zeichen, die der generische Wizard nicht sicher übernehmen kann."
}

set_env_value() {
  local key="$1"
  local value="$2"
  local temp
  temp="$(mktemp)"
  python3 - "${ENV_FILE}" "${temp}" "${key}" "${value}" <<'PY'
from __future__ import annotations
import sys
from pathlib import Path

source = Path(sys.argv[1])
target = Path(sys.argv[2])
key = sys.argv[3]
value = sys.argv[4]
if "\n" in value or "\r" in value:
    raise SystemExit("invalid env value")
lines = source.read_text(encoding="utf-8").splitlines() if source.exists() else []
prefix = key + "="
out = []
seen = False
for line in lines:
    if line.startswith(prefix):
        if not seen:
            out.append(prefix + value)
            seen = True
        continue
    out.append(line)
if not seen:
    out.append(prefix + value)
target.write_text("\n".join(out) + "\n", encoding="utf-8")
PY
  install -o "${APP_USER}" -g "${APP_USER}" -m 0600 "${temp}" "${ENV_FILE}"
  rm -f "${temp}"
}

command -v asterisk >/dev/null 2>&1 || die "Asterisk fehlt. Zuerst: sudo bash scripts/install_homepi_alerts.sh"
[[ -f "${ENV_FILE}" ]] || die "${ENV_FILE} fehlt. Zuerst den HomePi-Alert-Installer ausführen."
[[ -f "${PJSIP_MAIN}" ]] || die "${PJSIP_MAIN} wurde nicht gefunden."

echo "HomePi SIP/PJSIP Einrichtung"
echo "==========================="
echo
echo "Die Werte bekommst du im Kundenbereich deines VoIP-Anbieters."
echo "Der Wizard richtet einen ausgehenden Trunk ein; providerspezifische"
echo "Sonderoptionen können danach weiterhin in ${PJSIP_HOMEPI} ergänzt werden."
echo

read -r -p "SIP/Registrar-Server (z.B. sip.provider.de): " SIP_SERVER
read -r -p "SIP-Benutzername: " SIP_USERNAME
read -r -s -p "SIP-Passwort: " SIP_PASSWORD
echo
read -r -p "Absender/From-User [${SIP_USERNAME}]: " SIP_FROM_USER
SIP_FROM_USER="${SIP_FROM_USER:-${SIP_USERNAME}}"
read -r -p "Ziel-Handynummer im Providerformat (meist +49...): " ALERT_TARGET

SIP_SERVER="${SIP_SERVER#sip:}"
SIP_SERVER="${SIP_SERVER%/}"

require_token "SIP-Server" "${SIP_SERVER}"
require_token "SIP-Benutzername" "${SIP_USERNAME}"
require_token "From-User" "${SIP_FROM_USER}"
require_scalar "SIP-Passwort" "${SIP_PASSWORD}"
require_scalar "Zielnummer" "${ALERT_TARGET}"

[[ "${SIP_PASSWORD}" != *";"* ]] || die "Passwörter mit Semikolon werden vom generischen Wizard nicht geschrieben. Trunk bitte manuell konfigurieren."
[[ "${ALERT_TARGET}" =~ ^[+0-9*#]{3,32}$ ]] || die "Ungültiges Zielnummernformat."

timestamp="$(date +%Y%m%d-%H%M%S)"
backup_dir="/etc/asterisk/homepi-backup-${timestamp}"
install -d -o root -g root -m 0700 "${backup_dir}"
cp -a "${PJSIP_MAIN}" "${backup_dir}/pjsip.conf"
[[ -f "${PJSIP_HOMEPI}" ]] && cp -a "${PJSIP_HOMEPI}" "${backup_dir}/pjsip_homepi.conf"

transport_name="homepi-transport-udp"
transport_block='
[homepi-transport-udp]
type=transport
protocol=udp
bind=0.0.0.0
'

if grep -Eq '^\[transport-udp\][[:space:]]*
umask 077
temp_conf="$(mktemp)"
cat > "${temp_conf}" <<EOF
; HomePi outbound PJSIP trunk.
; Generated by scripts/configure_homepi_alerts.sh on $(date --iso-8601=seconds).
; Backup: ${backup_dir}
${transport_block}
[homepi-provider-auth]
type=auth
auth_type=userpass
username=${SIP_USERNAME}
password=${SIP_PASSWORD}

[homepi-provider-aor]
type=aor
contact=sip:${SIP_SERVER}
qualify_frequency=30

[homepi-provider]
type=endpoint
transport=${transport_name}
context=default
disallow=all
allow=alaw
allow=ulaw
outbound_auth=homepi-provider-auth
aors=homepi-provider-aor
from_user=${SIP_FROM_USER}
from_domain=${SIP_SERVER}
direct_media=no
rewrite_contact=yes
rtp_symmetric=yes
force_rport=yes

[homepi-provider-registration]
type=registration
transport=${transport_name}
outbound_auth=homepi-provider-auth
server_uri=sip:${SIP_SERVER}
client_uri=sip:${SIP_USERNAME}@${SIP_SERVER}
contact_user=${SIP_USERNAME}
retry_interval=30
forbidden_retry_interval=300
max_retries=20
EOF

install -o root -g asterisk -m 0640 "${temp_conf}" "${PJSIP_HOMEPI}"
rm -f "${temp_conf}"

if ! grep -Fxq "${INCLUDE_LINE}" "${PJSIP_MAIN}"; then
  printf '\n; HomePi managed outbound trunk\n%s\n' "${INCLUDE_LINE}" >> "${PJSIP_MAIN}"
fi

set_env_value HOMEPI_ALERT_TARGET "${ALERT_TARGET}"
set_env_value HOMEPI_ALERT_PJSIP_TRUNK "${TRUNK_NAME}"
set_env_value HOMEPI_ALERT_INTERACTIVE "true"
# Recovery remains PIN protected by the interactive assistant.
set_env_value HOMEPI_ALERTS_ENABLED "false"

echo
echo "Prüfe Asterisk-Konfiguration..."
if ! asterisk -rx "core reload" >/dev/null; then
  cp -a "${backup_dir}/pjsip.conf" "${PJSIP_MAIN}"
  if [[ -f "${backup_dir}/pjsip_homepi.conf" ]]; then
    cp -a "${backup_dir}/pjsip_homepi.conf" "${PJSIP_HOMEPI}"
  else
    rm -f "${PJSIP_HOMEPI}"
  fi
  asterisk -rx "core reload" >/dev/null 2>&1 || true
  die "Asterisk reload fehlgeschlagen. Backup wurde wiederhergestellt: ${backup_dir}"
fi

sleep 2
echo
asterisk -rx "pjsip show registrations" || true

echo
echo "SIP-Grundkonfiguration gespeichert."
echo "Automatische Alarmanrufe sind weiterhin AUS, bis der Test erfolgreich war."
echo
echo "Nächste Befehle:"
echo "  cd ${APP_DIR}"
echo "  .venv/bin/python scripts/homepi_alertctl.py doctor"
echo "  .venv/bin/python scripts/homepi_alertctl.py test-call"
echo
echo "Nach erfolgreichem Test:"
echo "  sudo sed -i 's/^HOMEPI_ALERTS_ENABLED=.*/HOMEPI_ALERTS_ENABLED=true/' ${ENV_FILE}"
echo "  sudo systemctl restart homepi-alert-monitor"
echo
echo "Asterisk-Backup: ${backup_dir}"
 "${PJSIP_MAIN}" 2>/dev/null \
  || { [[ -f "${PJSIP_HOMEPI}" ]] && grep -Eq '^\[transport-udp\][[:space:]]*
umask 077
temp_conf="$(mktemp)"
cat > "${temp_conf}" <<EOF
; HomePi outbound PJSIP trunk.
; Generated by scripts/configure_homepi_alerts.sh on $(date --iso-8601=seconds).
; Backup: ${backup_dir}
${transport_block}
[homepi-provider-auth]
type=auth
auth_type=userpass
username=${SIP_USERNAME}
password=${SIP_PASSWORD}

[homepi-provider-aor]
type=aor
contact=sip:${SIP_SERVER}
qualify_frequency=30

[homepi-provider]
type=endpoint
transport=${transport_name}
context=default
disallow=all
allow=alaw
allow=ulaw
outbound_auth=homepi-provider-auth
aors=homepi-provider-aor
from_user=${SIP_FROM_USER}
from_domain=${SIP_SERVER}
direct_media=no
rewrite_contact=yes
rtp_symmetric=yes
force_rport=yes

[homepi-provider-registration]
type=registration
transport=${transport_name}
outbound_auth=homepi-provider-auth
server_uri=sip:${SIP_SERVER}
client_uri=sip:${SIP_USERNAME}@${SIP_SERVER}
contact_user=${SIP_USERNAME}
retry_interval=30
forbidden_retry_interval=300
max_retries=20
EOF

install -o root -g asterisk -m 0640 "${temp_conf}" "${PJSIP_HOMEPI}"
rm -f "${temp_conf}"

if ! grep -Fxq "${INCLUDE_LINE}" "${PJSIP_MAIN}"; then
  printf '\n; HomePi managed outbound trunk\n%s\n' "${INCLUDE_LINE}" >> "${PJSIP_MAIN}"
fi

set_env_value HOMEPI_ALERT_TARGET "${ALERT_TARGET}"
set_env_value HOMEPI_ALERT_PJSIP_TRUNK "${TRUNK_NAME}"
set_env_value HOMEPI_ALERT_INTERACTIVE "true"
# Recovery remains PIN protected by the interactive assistant.
set_env_value HOMEPI_ALERTS_ENABLED "false"

echo
echo "Prüfe Asterisk-Konfiguration..."
if ! asterisk -rx "core reload" >/dev/null; then
  cp -a "${backup_dir}/pjsip.conf" "${PJSIP_MAIN}"
  if [[ -f "${backup_dir}/pjsip_homepi.conf" ]]; then
    cp -a "${backup_dir}/pjsip_homepi.conf" "${PJSIP_HOMEPI}"
  else
    rm -f "${PJSIP_HOMEPI}"
  fi
  asterisk -rx "core reload" >/dev/null 2>&1 || true
  die "Asterisk reload fehlgeschlagen. Backup wurde wiederhergestellt: ${backup_dir}"
fi

sleep 2
echo
asterisk -rx "pjsip show registrations" || true

echo
echo "SIP-Grundkonfiguration gespeichert."
echo "Automatische Alarmanrufe sind weiterhin AUS, bis der Test erfolgreich war."
echo
echo "Nächste Befehle:"
echo "  cd ${APP_DIR}"
echo "  .venv/bin/python scripts/homepi_alertctl.py doctor"
echo "  .venv/bin/python scripts/homepi_alertctl.py test-call"
echo
echo "Nach erfolgreichem Test:"
echo "  sudo sed -i 's/^HOMEPI_ALERTS_ENABLED=.*/HOMEPI_ALERTS_ENABLED=true/' ${ENV_FILE}"
echo "  sudo systemctl restart homepi-alert-monitor"
echo
echo "Asterisk-Backup: ${backup_dir}"
 "${PJSIP_HOMEPI}"; }; then
  transport_name="transport-udp"
  transport_block=""
fi

umask 077
temp_conf="$(mktemp)"
cat > "${temp_conf}" <<EOF
; HomePi outbound PJSIP trunk.
; Generated by scripts/configure_homepi_alerts.sh on $(date --iso-8601=seconds).
; Backup: ${backup_dir}
${transport_block}
[homepi-provider-auth]
type=auth
auth_type=userpass
username=${SIP_USERNAME}
password=${SIP_PASSWORD}

[homepi-provider-aor]
type=aor
contact=sip:${SIP_SERVER}
qualify_frequency=30

[homepi-provider]
type=endpoint
transport=${transport_name}
context=default
disallow=all
allow=alaw
allow=ulaw
outbound_auth=homepi-provider-auth
aors=homepi-provider-aor
from_user=${SIP_FROM_USER}
from_domain=${SIP_SERVER}
direct_media=no
rewrite_contact=yes
rtp_symmetric=yes
force_rport=yes

[homepi-provider-registration]
type=registration
transport=${transport_name}
outbound_auth=homepi-provider-auth
server_uri=sip:${SIP_SERVER}
client_uri=sip:${SIP_USERNAME}@${SIP_SERVER}
contact_user=${SIP_USERNAME}
retry_interval=30
forbidden_retry_interval=300
max_retries=20
EOF

install -o root -g asterisk -m 0640 "${temp_conf}" "${PJSIP_HOMEPI}"
rm -f "${temp_conf}"

if ! grep -Fxq "${INCLUDE_LINE}" "${PJSIP_MAIN}"; then
  printf '\n; HomePi managed outbound trunk\n%s\n' "${INCLUDE_LINE}" >> "${PJSIP_MAIN}"
fi

set_env_value HOMEPI_ALERT_TARGET "${ALERT_TARGET}"
set_env_value HOMEPI_ALERT_PJSIP_TRUNK "${TRUNK_NAME}"
set_env_value HOMEPI_ALERT_INTERACTIVE "true"
# Recovery remains PIN protected by the interactive assistant.
set_env_value HOMEPI_ALERTS_ENABLED "false"

echo
echo "Prüfe Asterisk-Konfiguration..."
if ! asterisk -rx "core reload" >/dev/null; then
  cp -a "${backup_dir}/pjsip.conf" "${PJSIP_MAIN}"
  if [[ -f "${backup_dir}/pjsip_homepi.conf" ]]; then
    cp -a "${backup_dir}/pjsip_homepi.conf" "${PJSIP_HOMEPI}"
  else
    rm -f "${PJSIP_HOMEPI}"
  fi
  asterisk -rx "core reload" >/dev/null 2>&1 || true
  die "Asterisk reload fehlgeschlagen. Backup wurde wiederhergestellt: ${backup_dir}"
fi

sleep 2
echo
asterisk -rx "pjsip show registrations" || true

echo
echo "SIP-Grundkonfiguration gespeichert."
echo "Automatische Alarmanrufe sind weiterhin AUS, bis der Test erfolgreich war."
echo
echo "Nächste Befehle:"
echo "  cd ${APP_DIR}"
echo "  .venv/bin/python scripts/homepi_alertctl.py doctor"
echo "  .venv/bin/python scripts/homepi_alertctl.py test-call"
echo
echo "Nach erfolgreichem Test:"
echo "  sudo sed -i 's/^HOMEPI_ALERTS_ENABLED=.*/HOMEPI_ALERTS_ENABLED=true/' ${ENV_FILE}"
echo "  sudo systemctl restart homepi-alert-monitor"
echo
echo "Asterisk-Backup: ${backup_dir}"
